### ISSUE TITLE
Demo project does not work in 6.10.8

### ISSUE THREAD

**Issue by RCatersels** [ivosturm/D3TreeView#1]
When opening the demo project in 6.10.3 it works. Then upgrading the model to 6.10.8 the demo project fails. The widget does not render. Only one object is show.

Regards,

Ronald
![2017-07-24 12_11_39-d3 treeview demo project - homepage](https://user-images.githubusercontent.com/10200344/28518751-53a38c14-7069-11e7-93b3-c98ae263de12.png)

**Comment by ivosturm** [comment]
Hi Ronald,

I checked the issue and it is related to different behavior from Mendix side related to self reference for 6.10.3 versus 6.10.8. 

Has anything changed in XPath handling for selfreferences in the Mendix range 6.10.3 - 6.10.8 that you know of?

**Comment by RCatersels** [comment]
No, we must have stumbled on a new bug. I checked the release notes. The only thing about self references I found was this: Using the reverse() method in an XPath constraint now works properly, even for self-references.
I would file a support ticket.

**Comment by ivosturm** [comment]
Hi Ronald, with some adjustments on the XPaths of the DS MF I got the demo app working again. See new release in the AppStore.

**Comment by RCatersels** [comment]
Thanks for the quick fix. Kudo's.

**Comment by RCatersels** [comment]
Hmm, I get an error from the appstore
![2017-07-25 10_01_35-treeview - mendix modeler 6 10 3 - c__users_ronal_documents_mendix_treeview_tree](https://user-images.githubusercontent.com/10200344/28561861-61bf3da4-7120-11e7-8438-326f6188c7c7.png)
Tried it from the appstore and from within the modeler.

**Comment by ivosturm** [comment]
My mistake. Can you try again?

EDIT: Tried myself and I see somehow the widget is NOT being included in the MPR even though it IS included in the widgets directory. Not sure what is happening there, since I got that problem again and again and never encountered this. Possibly a Mendix bug. Anyway; open the app and download the TreeView widget as well and it will work again!

**Comment by RCatersels** [comment]
For some reason the version selector tries to open a different modeler than the version published so you again got an error.
![2017-07-25 11_03_42-mendix modeler 6 10 3](https://user-images.githubusercontent.com/10200344/28564375-1cf84004-7129-11e7-9014-cd41238f2698.png)

**Comment by RCatersels** [comment]
I first thought I made a mistake but now when I download the version selector opens 6.10.3 while the project is in 6.10.9 again resulting in an error.
![2017-07-25 11_03_42-mendix modeler 6 10 3](https://user-images.githubusercontent.com/10200344/28564534-94f9f21e-7129-11e7-876b-7e09d34184ed.png)

**Comment by RCatersels** [comment]
Opeming in 6.10.9 does work so probably an app store setting you mist.

**Comment by RCatersels** [comment]
But the widget is working again and that is the main topic. Thanks for all your help.

**Comment by ivosturm** [comment]
No problem, thanks for the feedback. And you were right, forgot to select the upgraded 6.10.9 Modeler version when publishing, so the Version selector kept directing to 6.10.3. Fixed in a patch release now as well, so all should be well now.
