### ISSUE TITLE
Request: Different node styling based on Enumeration

### ISSUE THREAD

**Issue by MarkMellink** [ivosturm/D3TreeView#5]
Hi Ivo,

I was wondering if it was possible to customize the node styling using an Enumeration in Mendix? Maybe by allowing us to specifiy an Enumeration and adding that to the class of the node? This would allow us to style the nodes slightly different based on an Enumeration Value. In my case I'd like to use it to show 'warning' nodes vs. 'healthy' nodes.

Thanks,

Mark

**Comment by MarkMellink** [comment]
Also saw you released this one too, will try it out! Thanks for the fast updates!

**Comment by ivosturm** [comment]
Hi Mark,

I had some issues with the new Mendix AppStore, not being able to publish it today. I did publish the new MPK file in GitHub, so if you want to test the new features today, be sure to get the release 2.2.0 from GitHub. I will sort out the Mendix AppStore issue later this week.

Please let me know whether the bugfix and new features are working as expected!

Cheers!

Outlook voor iOS<https://aka.ms/o0ukef> downloaden
________________________________
Van: Mark Mellink <notifications@github.com>
Verzonden: Sunday, January 10, 2021 1:06:48 PM
Aan: ivosturm/D3TreeView <D3TreeView@noreply.github.com>
CC: Subscribed <subscribed@noreply.github.com>
Onderwerp: Re: [ivosturm/D3TreeView] Request: Different node styling based on Enumeration (#5)


Also saw you released this one too, will try it out! Thanks for the fast updates!

**Comment by ivosturm** [comment]
@MarkMellink I published a new version of both the widget and the testpoject to the Mendix Marketplace. Can you let me know for the features delivered+ bug fixed, whether the changes are working well?

**Comment by MarkMellink** [comment]
Works perfectly, thanks Ivo!
